# Generated by Django 2.0.6 on 2019-09-16 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('contactfio', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('flat', models.CharField(blank=True, max_length=50)),
                ('cabinet', models.CharField(blank=True, max_length=10)),
                ('date_in', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('vacation', models.BooleanField(default=False)),
                ('time_start', models.CharField(blank=True, max_length=10)),
                ('time_end', models.CharField(blank=True, max_length=10)),

            ],
        ),
        migrations.CreateModel(
            name='Prioritet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('datetask', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('daterun', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Master')),
                ('prioritet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Prioritet')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Status'),
        ),
        migrations.AddField(
            model_name='master',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Spec'),
        ),
    ]
