# Generated by Django 2.0.6 on 2019-09-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='master',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
