# Generated by Django 2.0.6 on 2019-09-27 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0006_auto_20190927_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='user',
        ),
        migrations.AddField(
            model_name='firma',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
